services:
  dagster-webserver:
    image: ghcr.io/laurimaila/electricity-pipeline:latest
    restart: always
    environment:
      - ENTSOE_API_TOKEN=${ENTSOE_API_TOKEN}
      - POSTGRES_CONNECTION_STRING=${POSTGRES_CONNECTION_STRING}
      - DAGSTER_POSTGRES_USER=${DAGSTER_POSTGRES_USER}
      - DAGSTER_POSTGRES_PASSWORD=${DAGSTER_POSTGRES_PASSWORD}
      - DAGSTER_POSTGRES_DB=${DAGSTER_POSTGRES_DB}
      - DAGSTER_POSTGRES_HOSTNAME=${DAGSTER_POSTGRES_HOSTNAME}
      - DAGSTER_HOME=/app
      - PYTHONPATH=/app
    command: ["dagster-webserver", "-h", "0.0.0.0", "-p", "3000"]

  dagster-daemon:
    image: ghcr.io/laurimaila/electricity-pipeline:latest
    restart: always
    environment:
      - ENTSOE_API_TOKEN=${ENTSOE_API_TOKEN}
      - POSTGRES_CONNECTION_STRING=${POSTGRES_CONNECTION_STRING}
      - DAGSTER_POSTGRES_USER=${DAGSTER_POSTGRES_USER}
      - DAGSTER_POSTGRES_PASSWORD=${DAGSTER_POSTGRES_PASSWORD}
      - DAGSTER_POSTGRES_DB=${DAGSTER_POSTGRES_DB}
      - DAGSTER_POSTGRES_HOSTNAME=${DAGSTER_POSTGRES_HOSTNAME}
      - DAGSTER_HOME=/app
      - PYTHONPATH=/app
    command: ["dagster-daemon", "run"]
